### ISSUE TITLE
only last word of input text preserved

### ISSUE THREAD

**Issue by geza-kiss** [jpellman/textgridR#5]
I was very glad to find your package, and started using it right away.
Then I realized that the start of each text is trimmed off, and only the last word is preserved.
I created a small TextGrid with only one tier, and only one text in that tier, and the error is present in that as well. I would appreciate a bug correction.

[1.TextGrid.txt](https://github.com/jpellman/textgridR/files/222175/1.TextGrid.txt)

**Comment by jpellman** [comment]
Hi geza,

textgridR was a project I wrote a while back and which I haven't been able
to devote much time to in recent years.  I'll try to look into this glitch,
but I can't make any guarantees given the time I need to devote to my
current engagements.  If I can't solve this within 2-3 days, I won't be
able to return to it until a while later.

Just to clarify, you are encountering a problem with exporting textgrid
files (rather than importing), correct?

**Comment by geza-kiss** [comment]
Hi,
No, it happens when you load (or import) the TextGrid files.
Géza

**Comment by jpellman** [comment]
Hi @geza-kiss ,

I've updated the code if you'd like to try loading in your TextGrid now.
